on:
  push:
    branches:
      - '*'  # Triggers the workflow on push to any branch

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOTNET_VERSION: 7.x.x
      NEXUS_SOURCE: https://hubrepopanda.pandatech.it/repository/nuget-hosted/index.json
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      DOCKER_REPO: repopanda.pandatech.it/pandatech/repository/pandatech/dev
      SERVICE_NAME: ${{ github.event.repository.name }}
      K8S_NAMESPACE: dev
      K8S_CLUSTER_ADDRESS: https://10.0.8.11:6443

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: false

      - name: remove old nuget sources
        run: |
          dotnet nuget remove source pandatech
          dotnet nuget remove source nuget.org
        continue-on-error: true

      - name: Add nuget source
        run: |
          dotnet nuget add source ${{ env.NEXUS_SOURCE }} -n pandatech -u ${{ secrets.nexus_username }} -p ${{ secrets.nexus_password }} --store-password-in-clear-text
        continue-on-error: true

      - name: Add nuget source
        run: |
          dotnet nuget add source ${{ env.NUGET_SOURCE }} -n nuget.org
        continue-on-error: true

      - name: Restore
        run: dotnet restore --verbosity normal --no-cache --force --disable-parallel

      - name: Build
       # if: github.ref != 'refs/heads/development'
        run: dotnet build --no-restore --verbosity normal --configuration Release
      
      #      - name: Test
      #        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish
        run: dotnet publish --no-build --verbosity normal --configuration Release --output ./publish

      - name: Build Docker Image
        run: |
          DOCKER_TAG=$(date +'%Y%m%d%H%M%S')-$GITHUB_RUN_NUMBER
          DOCKER_REPO_PROD=repopanda.pandatech.it/pandatech/repository/pandatech/prod
          DOCKER_REPO_DEV=repopanda.pandatech.it/pandatech/repository/pandatech/dev
          DOCKER_REPO_QA=repopanda.pandatech.it/pandatech/repository/pandatech/qa
          DOCKER_REPO_STAGING=repopanda.pandatech.it/pandatech/repository/pandatech/staging

          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DOCKER_REPO=${DOCKER_REPO_PROD}
          elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
            DOCKER_REPO=${DOCKER_REPO_DEV}
          elif [ "${{ github.ref }}" == "refs/heads/qa" ]; then
            DOCKER_REPO=${DOCKER_REPO_QA}
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            DOCKER_REPO=${DOCKER_REPO_STAGING}
          else
            echo "Unsupported branch for deployment."
            exit 1
          fi

          docker build . -t $DOCKER_REPO/${{ env.SERVICE_NAME }}:${DOCKER_TAG}
          docker tag $DOCKER_REPO/${{ env.SERVICE_NAME }}:${DOCKER_TAG} $DOCKER_REPO/${{ env.SERVICE_NAME }}:latest
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      - name: Login to Nexus
        run: docker login ${{ env.DOCKER_REPO }} -u ${{ secrets.nexus_username }} -p ${{ secrets.nexus_password }}

      - name: Push Docker Image to Nexus
        run: |
          DOCKER_TAG=${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_REPO }}/${{ env.SERVICE_NAME }}:${DOCKER_TAG}
          docker push ${{ env.DOCKER_REPO }}/${{ env.SERVICE_NAME }}:latest

      - name: Update Deployment
        if: github.ref != 'refs/heads/main'
        run: |
          export KUBECONFIG=/home/runner/.kube/config
          sed -i "s|${{ env.DOCKER_REPO }}/${{ env.SERVICE_NAME }}:IMAGE_TAG_PLACEHOLDER|${{ env.DOCKER_REPO }}/${{ env.SERVICE_NAME }}:${{ env.DOCKER_TAG }}|g" ./kubernetes/deployment.yaml
          kubectl apply -f ./kubernetes/deployment.yaml -n ${{ env.K8S_NAMESPACE }}
        env:
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          K8S_CLUSTER_ADDRESS: ${{ env.K8S_CLUSTER_ADDRESS }}

      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
